bitrise stack related update - better test in bitrise.yml & is_requires_admin_user=true

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -1,14 +1,31 @@
-format_version: 0.9.10
+format_version: 1.0.0
 default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
-
-app:
-  envs:
-  # define these in your .bitrise.secrets.yml
-  - path:
-  - with_sudo:
 
 workflows:
   test:
     steps:
+    - script:
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -e
+            set -v
+            mkdir -p ./_tmp/subfold
+            echo 'hi' > ./_tmp/hi.txt
+            echo 'test' > ./_tmp/subfold/test.txt
     - path::./:
         inputs:
+        - path: ./_tmp
+        - with_sudo: "false"
+    - script:
+        inputs:
+        - content: |-
+            #!/bin/bash
+            if [[ -f "./_tmp/hi.txt" || -f "./_tmp/subfold/test.txt" ]] ; then
+              echo "File found - ERROR"
+              exit 1
+            fi
+            if [ -d ./_tmp ] ; then
+              echo "Dir found - ERROR"
+              exit 1
+            fi
